---

- name: Install trizen
  shell: |
    yaourt -S --noconfirm --needed trizen
  become: no

- name: Install arch dependencies via trizen
  shell: |
    trizen -S --noconfirm --needed \
        dspdfviewer \
        etcher \
        google-chrome \
        masterpdfeditor \
        cherrytree \
        burpsuite \
        ttf-ms-fonts \
        radare2-git \
        noson-app \
        pdftk \
        rambox-bin \
        spotify \
        wxhexeditor-git
  become: no
