---

- name: Install general dependencies via package manager
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - arandr
    - blueman
    - cmake
    - dunst
    - feh
    - git
    - gimp
    - gparted
    - i3-wm
    - lxappearance
    - nautilus
    - pass
    - ranger
    - rofi
    - scrot
    - w3m
    - wicd-gtk
    - xclip
    - xdotool
    - xss-lock
    - zsh

- name: Installing python (Arch)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2
    - python2-pip
    - python
    - python-pip
  when: ansible_distribution == "Archlinux"

- name: Installing python (Debian/Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7
    - python-pip
    - python3
    - python3-pip
  when: ansible_distribution != "Archlinux"

- name: Update pip packages
  shell: |
    pip2 install -U pip && pip3 install -U pip

- name: Install pip2 dependencies
  pip:
    name: i3ipc
    executable: pip2

- name: Install pip3 dependencies
  pip:
    name: pipenv i3ipc yapf pylint
    executable: pip3

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: debian.yml
  when: "ansible_distribution == 'Debian' or 'Kali' in ansible_distribution"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
