---

- name: Install general dependencies via package manager
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - ranger
    - zsh

- include_tasks: ubuntu-server.yml
  when: ansible_distribution == "Ubuntu"

- name: Clone Dotfiles repo
  git:
    repo: 'https://github.com/ps1337/Dotfiles.git'
    dest: ~/.dotfiles
    update: yes
    recursive: yes

- name: Clone shared secrets repo
  git:
    repo: "{{ shared_repo_url }}"
    dest: "~/.dotfiles/shared-secrets"
    update: yes
    recursive: yes

- name: Update submodules
  command: git submodule update --init --recursive
  args:
    chdir: ~/.dotfiles

- import_tasks: symlinks-server.yml
  vars:
    srcBase: "/root"
    dstBase: "/root"

- name: Install fzf
  shell: |
    echo "yyn" | ~/.dotfiles/fzf/install

- name: Call vim role
  include_role:
    name: vim
