---

- name: Install pip2 dependencies for neovim
  shell: |
    pip2 install neovim msgpack-python jedi ansible-lint autopep8 unidecode future

- name: Install pip3 dependencies for neovim
  shell: |
    pip3 install neovim msgpack-python jedi ansible-lint autopep8 future

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: debian.yml
  when: "ansible_distribution == 'Debian' or 'Kali' in ansible_distribution"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
