---

- name: Install general dependencies via package manager
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - ranger
    - zsh
    - wget
    - curl
    - tmux
    - cmake
    - zsh
    - gcc
    - g++

- name: Installing python (Arch)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2
    - python2-pip
    - python
    - python-pip
  when: ansible_distribution == "Archlinux"

- name: Installing python (Debian/Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7
    - python-pip
    - python3
    - python3-pip
  when: ansible_distribution != "Archlinux"

- include_tasks: ubuntu-server.yml
  when: ansible_distribution == "Ubuntu"

- name: Clone Dotfiles repo
  git:
    repo: 'https://github.com/ps1337/Dotfiles.git'
    dest: ~/.dotfiles
    update: yes
    recursive: yes

- name: Clone shared repo
  git:
    repo: "{{ shared_repo_url }}"
    dest: "~/.dotfiles/shared-secrets"
    update: yes
    recursive: yes
  when: shared_repo_url is defined


- name: Update submodules
  command: git submodule update --init --recursive
  args:
    chdir: ~/.dotfiles

- import_tasks: symlinks-server.yml
  vars:
    srcBase: "/root"
    dstBase: "/root"

- name: Install fzf
  shell: |
    echo "yyn" | ~/.dotfiles/fzf/install

- name: Call vim role
  include_role:
    name: vim
