---

- name: Install server packages (Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pygments
    - ranger
    - w3m
    - w3m-img
    - silversearcher-ag
    - powerline
    - python3-powerline
